[platformio]
default_envs = genericSTM32F401CC

[env:genericSTM32F401CC]
platform = ststm32
board = genericSTM32F401CC
framework = cmsis
upload_protocol = stlink
debug_tool = stlink
build_type = debug

#board_build.ldscript = STM32F401CCFX_FLASH_Sector2.ld

board_build.fpu = fpv4-sp-d16
board_build.float-abi = hard



build_src_filter = 
    +<*> 
    +<../lib/CubeAI/network/> 
    +<../lib/CMSIS_DSP_wrapper/>
    

build_flags = 
    -O2
    -DSTM32F401xC
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -ffast-math
    -Wall
    -Wextra
    -Ilib/CubeAI/Inc
    -Ilib/CubeAI/network
    -Imodels
    -DARM_MATH_CM4
    -Ilib/FreeRTOS/include
    -Ilib/FreeRTOS/portable/GCC/ARM_CM4F
    
    -I/home/ehab/.platformio/packages/framework-cmsis/CMSIS/DSP/Include
    -I/home/ehab/.platformio/packages/framework-cmsis/CMSIS/Core/Include

build_unflags = -Os -O0 -mfloat-abi=soft -msoft-float

debug_build_flags = -Og -ggdb3 -g3

extra_scripts = pre:link_cubeai.py

check_tool = cppcheck
check_flags = cppcheck: --enable=all
